### PR TITLE
Add Syntax Highlighting

### PR DESCRIPTION
**Pull request by theprivileges**
- Add a minimum css reset.
- Add box-sizing property where appropriate.
- Add HTML5 input properties.
- Create helper method to display error messages.
- Create helper method to display DQL result.
- Use a better font for the results.
- Add PrismJS to the codebase.
- Add method to change the submit button value to Loading.
- Better visual for the submit button.
## dqlrunner_and_1__npm_start__node_

screen shot 2016-05-05 at 16 41 15

### CODE REVIEW

**Comment by theprivileges** [comment]
@nicholascloud can you run this on your local instance, and let me know if there are any issues. Please?

**Comment by nicholascloud** [comment]
@theprivileges No problems here, and it looks sharp!

**Comment by theprivileges** [comment]
@nicholascloud I'm merging this in.

**Comment by nicholascloud** [comment]
:+1:

**Pull request merged**
